#!/usr/bin/env python3
import itertools, requests
rs = requests.Session()
scales = ["", "@2x"]
urls = [
    "http://tile.cartago.io/styles/cartago-streets/{z}/{x}/{y}{scale}.png?apikey=tdegbzkx1wshqdvy",
    "http://tile.cartago.io/styles/cartago-streets/{z}/{x}/{y}{scale}.png?apikey=tdegbzkx1wshqdvy",
]
def p(message):
    print(message, end="", flush=True)
for z in range(9):
    xs = range(2**z)
    ys = range(2**z)
    left = len(xs) * len(ys) * len(scales) * len(urls)
    p("\n{:d}:{:d}".format(z, left))
    for item in itertools.product(xs, ys, scales, urls):
        x, y, scale, url = item
        left = left - 1
        p("{:d}:{:d}".format(z, left) if left % 100 == 0 else ".")
        response = rs.get(url.format(**locals()))
        if response.status_code != 200:
            p("HTTP:{:d}".format(response.status_code))
