#!/usr/bin/env python3
import itertools, requests
rs = requests.Session()
scales = ["", "@2x"]
urls = [
    "http://tile.cartago.io/styles/cartago-streets/{z}/{x}/{y}{scale}.png?apikey=tdegbzkx1wshqdvy",
    "http://tile.cartago.io/styles/cartago-streets/{z}/{x}/{y}{scale}.png?apikey=tdegbzkx1wshqdvy",
]
def p(message):
    print(message, end="", flush=True)
for z in range(8):
    p("\n{:d}: {:d} ".format(z, (2**z)*(2**z)*2))
    xs = range(2**z)
    ys = range(2**z)
    for item in itertools.product(xs, ys, scales, urls):
        x, y, scale, url = item
        p(".")
        response = rs.get(url.format(**locals()))
        if response.status_code != 200:
            p(response.status_code)
