#!/bin/sh
for STYLE in cartago-streets cartago-streets-english; do
    for SCALE in "" @2x @3x @4x; do
        PIDS=""
        for ROUND in $(seq 100); do
            Z=16
            X=$(shuf -n1 -i0-65536)
            Y=$(shuf -n1 -i0-65536)
            URL="http://localhost:8001/styles/$STYLE/$Z/$X/$Y$SCALE.png"
            echo "$URL"
            curl -s -o /dev/null "$URL" &
            PIDS="$PIDS $!"
            sleep 0.001
        done
        echo "Waiting for requests to complete..."
        wait $PIDS
    done
done
